# docker-compose -f servicios.yml -p servicios up

services:
  servicio1:
    image: servicio1
    container_name: servicio1
    ports:
      - 5000:5000
    networks:
      - servicios

  servicio2:
    image: servicio2
    container_name: servicio2
    ports:
      - 5001:5000
    networks:
      - servicios
  
  servicio3:
    image: servicio3
    container_name: servicio3
    ports:
      - 5002:5000
    networks:
      - servicios
  
  servicio4:
    image: servicio4
    container_name: servicio4
    ports:
      - 5003:5000
    networks:
      - servicios

networks:
  servicios:
    driver: bridge